### PR TITLE
chore: rename zkConnect to Sismo Connect, improvements to README.md

### PR DESCRIPTION
**Pull request by AdamSchinzel**
While going through the docs I found some content with the old name so I renamed it.

There are still two pages that contain 'zkConnect' references: `technical-documentation/data-vault-app.md` and `technical-documentation/sismo-connect/react.md`. I assume it would make sense to rename the first page if the picture also contains Sismo Connect (since almost all of the text is related to the image which I can't change) and the second page mainly contains hrefs with 'zkConnect'. The paths to the files on the website are probably only editable through the Gitbook app.

I also made some small improvements to README.md.

### CODE REVIEW

**Comment by wojventures** [comment]
hey @dhadrien this is really important please merge asap

**Comment by leosayous21** [comment]
@AdamSchinzel Thanks a lot for this! 💜

**Comment by MartinGbz** [comment]
Hey @AdamSchinzel @wojtekwtf thanks a lot guys 🙏
I reproduced the changes on GitBook directly, it's update!

**Comment by AdamSchinzel** [comment]
> Hey @AdamSchinzel @wojtekwtf thanks a lot guys 🙏 I reproduced the changes on GitBook directly, it's update!

Awesome!

**Pull request merged**
